# Generated by Django 3.0.4 on 2020-04-04 13:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('event_type', models.CharField(choices=[('Birth Day', 'Birth Day'), ('Marriage', 'Marriage')], max_length=20)),
                ('package', models.IntegerField(choices=[(265000, 'Silver'), (300000, 'Gold')])),
                ('cleaning_charges', models.IntegerField(blank=True, default=0, null=True)),
                ('electricity_consumption', models.IntegerField(blank=True, default=0, null=True)),
                ('property_damage_charges', models.IntegerField(blank=True, default=0, null=True)),
                ('advance_paid', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muhurt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
